---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  coobooks_path:
    - cookbooks
  encrypted_data_bag_secret_key_path: "../../encrypted_data_bag_secret"
  data_bags_path: "../../data_bags"

platforms:
  - name: bento/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[guacamole]
