name 'guacamole'
maintainer 'Michael Leikind'
maintainer_email 'bigmyx@dango.me'
license 'Apache 2.0'
description 'Installs/Configures guacamole'
long_description 'Installs/Configures guacamole-server, an HTML5 remote desktop client thing'
version '0.1.2'

depends 'tomcat'
depends 'java'
